### ISSUE TITLE
Not working with FlutterFragmentActivity

### ISSUE THREAD

**Issue by minhtritc97** [developerjamiu/smart-text-flutter#6] opened 2024-05-24 03:08 UTC

**Comment by developerjamiu** [comment] 2024-06-26 06:05
Can you explain this in more detail? What your use case is and how to reproduce.

**Comment by developerjamiu** [comment] 2024-11-28 05:58
Closing as I am unable to reproduce. Feel free to reopen when you have a way to reproduce.

**Closed as completed by developerjamiu** 2024-11-28 05:58 UTC
